import type { Metadata } from 'next';
import { Alex_Brush, Mr_De_Haviland, Poppins } from 'next/font/google';
import Script from 'next/script';
import './globals.css';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '600'],
    variable: '--font-poppins',
});

const alexBrush = Alex_Brush({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-alex-brush',
});

const deHaviland = Mr_De_Haviland({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-de-haviland',
});

export const metadata: Metadata = {
    title: 'Leia & Joel Wedding',
    // description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={`${poppins.variable} ${alexBrush.variable} ${deHaviland.variable}`}
        >
            <head>
                <Script
                    src="https://kit.fontawesome.com/659f0bc72c.js"
                    crossOrigin="anonymous"
                />
            </head>
            <body>{children}</body>
        </html>
    );
}
