import type { Metadata } from 'next';
import { Alex_Brush, Mr_De_Haviland, Poppins, Varela_Round } from 'next/font/google';
import Script from 'next/script';
import './styles/globals.css';

const sans = Poppins({
    subsets: ['latin'],
    weight: ['400', '600'],
    variable: '--font-sans',
});

const serif = Alex_Brush({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-serif',
});

const cursive = Mr_De_Haviland({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-cursive',
});

const numbers = Varela_Round({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-numbers',
});

export const metadata: Metadata = {
    title: 'Leia & Joel Wedding',
    // description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="en"
            className={`${sans.variable} ${serif.variable} ${cursive.variable} ${numbers.variable}`}
        >
            <head>
                <Script
                    src="https://kit.fontawesome.com/659f0bc72c.js"
                    crossOrigin="anonymous"
                />
            </head>
            <body>{children}</body>
        </html>
    );
}
